# please set the file path
output_dir: None
train_data_file: None
dev_data_file: None

model_name_or_path: "cl-tohoku/bert-base-japanese-whole-word-masking"
logging_steps: 2500
save_steps: 5000

# device (we used 4 GPUs)
fp16: True
fp16_opt_level: "O1"
no_cuda: False

# hyper-parameters
per_gpu_train_batch_size: 8
per_gpu_eval_batch_size: 16
gradient_accumulation_steps: 64
learning_rate: 2e-5
weight_decay: 0.01
num_train_epochs: 20
max_steps: 30000
warmup_steps: 5000
seed: int = 42

# model specific parameters
model_type: 'pzero'
